title: Rz1027 Website
description: Cybersecurity and AI integrator | Penetration Tester | I share whatever I find interesting
show_downloads: true
google_analytics:
theme: jekyll-theme-hacker
timezone: asia/beirut
url: rz1027.github.io

social:
  name: Rz1027
  discord: rz1027
  twitter: Rz_Ai_